# Generated by Django 2.1.5 on 2019-02-05 15:36

from django.db import migrations
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
