# Generated by Django 2.1.5 on 2019-01-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
       
    ]
